apiVersion: apps/v1
kind: Deployment
metadata:
  name: olive-back
  labels:
    app: olive-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: olive-back
  template:
    metadata:
      labels:
        app: olive-back
    spec:
      containers:
        - name: olive-back
          image: sha256:68cd66025f0f74c083021f9ca0d19d6845d5e979ce74b622f927facf31d41e12  # ✅ ECR 이미지 사용
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
