AWSTemplateFormatVersion: '2010-09-09'
Description: "IAM 역할 및 정책"

Resources:
  EKSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EKSRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

Outputs:
  EKSRoleArn:
    Value: !GetAtt EKSRole.Arn
