apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jg-develop
  namespace: argocd  # ArgoCD 배포된 네임스페이스
spec:
  project: default
  source:
    repoURL: https://github.com/CJ-Jungle-gym/kuberneties.git 
    targetRevision: HEAD  # 최신 커밋 기준
    path: manifest  # Git 저장소 내 배포 매니페스트 경로
  destination:
    server: https://kubernetes.default.svc  # 클러스터 주소
    namespace: jg-develop  # 배포할 네임스페이스
  syncPolicy:
    automated:  # 자동 동기화 활성화
      prune: true  # 불필요한 리소스 삭제
      selfHeal: true  # 상태 복구
