apiVersion: apps/v1
kind: Deployment
metadata:
  name: olive-back
  labels:
    app: olive-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: olive-back
  template:
    metadata:
      labels:
        app: olive-back
    spec:
      containers:
        - name: olive-back
          image: 156041411267.dkr.ecr.ap-northeast-2.amazonaws.com/olive-back:v1
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: FRONTEND_URL
              value: "http://olive-frontend-service:3000"  # 프론트엔드 서비스의 DNS 이름 (Kubernetes 서비스 이름)
